name = "TemporalMixtureModels"
uuid = "04cebb6a-72a2-4d9b-bd91-f7dfea97eb3c"
version = "2.0.0"
authors = ["max-de-rooij <54850292+max-de-rooij@users.noreply.github.com>"]

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RequiredInterfaces = "97f35ef4-7bc5-4ec1-a41a-dcc69c7308c6"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Convex = "0.16"
Distributions = "0.25.122"
Hungarian = "0.7"
LinearAlgebra = "1.10 - 1.12"
LinearSolve = "3.40 - 3.46"
ProgressMeter = "1.10 - 1.12"
Random = "1.10 - 1.12"
RequiredInterfaces = "0.1.7"
SCS = "2.2"
Statistics = "1.10 - 1.12"
julia = "1.10 - 1.12"
